/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NBadgeAuthInterface } from "./NBadgeAuthInterface";
export type { NBadgeAuthorityInterface } from "./NBadgeAuthorityInterface";
