# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["node_modules", "lib"]
optimizer = true
via-ir = false
optimizer_runs = 200
solc = "0.8.17"
out = "out"
src = "src"
test = "test/forge"
cache_path = 'cache'
script='script/forge'

[profile.ci]
fuzz_runs = 1_000
verbosity = 4