# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["node_modules", "lib"]
optimizer = true
via-ir = false
optimizer_runs = 150
solc = "0.8.17"
out = "out"
src = "src"
test = "test/forge"
cache_path = 'cache'
script='script/forge'
fs_permissions = [{ access = "read", path="./" }]

[rpc_endpoints]
goerli="${GOERLI_RPC_URL}"
polygon="${POLYGON_RPC_URL}"
mumbai="${MUMBAI_RPC_URL}"

[etherscan]
goerli={ key = "${ETHERSCAN_API_KEY}" }
polygon={ key = "${POLYGONSCAN_API_KEY}" }
mumbai={ key = "${POLYGONSCAN_API_KEY}" }

[profile.ci]
fuzz_runs = 1_000
verbosity = 4


