/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scalableLikertEnforcementSol from "./ScalableLikertEnforcement.sol";
export type { scalableLikertEnforcementSol };
