/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NBadgeAuthInterface,
  NBadgeAuthInterfaceInterface,
} from "../../../../src/interfaces/auth/NBadgeAuthInterface";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract NBadgeAuthority",
        name: "newAuthority",
        type: "address",
      },
    ],
    name: "AuthorityUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
] as const;

export class NBadgeAuthInterface__factory {
  static readonly abi = _abi;
  static createInterface(): NBadgeAuthInterfaceInterface {
    return new utils.Interface(_abi) as NBadgeAuthInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NBadgeAuthInterface {
    return new Contract(address, _abi, signerOrProvider) as NBadgeAuthInterface;
  }
}
