/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NBadgeAuthorityInterface,
  NBadgeAuthorityInterfaceInterface,
} from "../../../../src/interfaces/auth/NBadgeAuthorityInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "functionSig",
        type: "bytes4",
      },
    ],
    name: "canCall",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NBadgeAuthorityInterface__factory {
  static readonly abi = _abi;
  static createInterface(): NBadgeAuthorityInterfaceInterface {
    return new utils.Interface(_abi) as NBadgeAuthorityInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NBadgeAuthorityInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NBadgeAuthorityInterface;
  }
}
