/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NBadge } from "./NBadge";
export type { NBadgeAuth } from "./NBadgeAuth";
export type { NBadgeAuthority } from "./NBadgeAuthority";
