/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155FreeMint } from "./ERC1155FreeMint";
export type { ERC20FreeMint } from "./ERC20FreeMint";
