/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multicall3Sol from "./Multicall3.sol";
export type { multicall3Sol };
export type { ERC1155FreeMint } from "./ERC1155FreeMint";
export type { ERC20FreeMint } from "./ERC20FreeMint";
