/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auth from "./auth";
export type { auth };
import type * as enforcement from "./enforcement";
export type { enforcement };
export type { LaborMarketFactoryInterface } from "./LaborMarketFactoryInterface";
export type { LaborMarketInterface } from "./LaborMarketInterface";
