/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  LaborMarketFactoryInterface,
  LaborMarketFactoryInterfaceInterface,
} from "../../../src/interfaces/LaborMarketFactoryInterface";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "marketAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "deployer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "LaborMarketCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_deployer",
        type: "address",
      },
      {
        internalType: "contract EnforcementCriteriaInterface",
        name: "_criteria",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_auxilaries",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_alphas",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_betas",
        type: "uint256[]",
      },
    ],
    name: "createLaborMarket",
    outputs: [
      {
        internalType: "address",
        name: "laborMarketAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class LaborMarketFactoryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): LaborMarketFactoryInterfaceInterface {
    return new utils.Interface(_abi) as LaborMarketFactoryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LaborMarketFactoryInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LaborMarketFactoryInterface;
  }
}
